name: Build on creation of a new release
on:
  release:
    types: [published]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          platforms: linux/arm64
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          push: true
          tags: ghcr.io/benjamin-maynard/kubernetes-cloud-mysql-backup:latest,ghcr.io/benjamin-maynard/kubernetes-cloud-mysql-backup:${{ steps.get_version.outputs.VERSION }}
